<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\SaveHomeBannerRequest;
use App\Models\Category;
use App\Models\HomeBanner;
use App\Models\Product;
use App\Models\Tag;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

/**
 * Manages every homepage slider item — hero slides and the benefits strip
 * share this controller/table, split by `section` (?section=hero|benefit).
 */
class HomeBannerController extends Controller
{
    public function index(Request $request): View
    {
        $section = $this->section($request->query('section'));

        return view('admin.cms.banners.index', [
            'section' => $section,
            'banners' => HomeBanner::query()->section($section)->with(['product:id,name', 'category:id,name', 'tag:id,name'])->ordered()->paginate(20)->withQueryString(),
        ]);
    }

    public function create(Request $request): View
    {
        return view('admin.cms.banners.create', ['section' => $this->section($request->query('section'))] + $this->formOptions());
    }

    public function store(SaveHomeBannerRequest $request): RedirectResponse
    {
        $banner = HomeBanner::create($this->payload($request));

        return redirect()->route('admin.cms.banners.index', ['section' => $banner->section])->with('success', 'Saved.');
    }

    public function edit(HomeBanner $banner): View
    {
        return view('admin.cms.banners.edit', ['banner' => $banner, 'section' => $banner->section] + $this->formOptions());
    }

    public function update(SaveHomeBannerRequest $request, HomeBanner $banner): RedirectResponse
    {
        $banner->update($this->payload($request, $banner));

        return redirect()->route('admin.cms.banners.index', ['section' => $banner->section])->with('success', 'Updated.');
    }

    public function toggle(HomeBanner $banner): RedirectResponse
    {
        $banner->update(['status' => $banner->status === 'active' ? 'inactive' : 'active']);

        return back()->with('success', '"'.($banner->title ?: 'Item').'" is now '.$banner->status.'.');
    }

    public function destroy(HomeBanner $banner): RedirectResponse
    {
        $this->deleteFiles([$banner->image, $banner->mobile_image]);

        $section = $banner->section;
        $banner->delete();

        return redirect()->route('admin.cms.banners.index', ['section' => $section])->with('success', 'Deleted.');
    }

    private function section(?string $value): string
    {
        return in_array($value, HomeBanner::SECTIONS, true) ? $value : HomeBanner::SECTION_HERO;
    }

    /** @param  array<int, ?string>  $paths */
    private function deleteFiles(array $paths): void
    {
        foreach ($paths as $path) {
            if ($path) {
                Storage::disk('public')->delete($path);
            }
        }
    }

    /** @return array<string, mixed> */
    private function payload(SaveHomeBannerRequest $request, ?HomeBanner $existing = null): array
    {
        $data = $request->safe()->except(['image', 'mobile_image', 'remove_image', 'remove_mobile_image']);
        $data['sort_order'] = $data['sort_order'] ?? 0;
        $data['text_position'] = $data['text_position'] ?? 'left';
        $data['opens_new_tab'] = $request->boolean('opens_new_tab');

        // Keep only the target that matches the chosen destination type, so
        // switching a banner from "product" to "url" never leaves a stale id.
        foreach (['product' => 'product_id', 'category' => 'category_id', 'tag' => 'tag_id', 'url' => 'link_url'] as $type => $column) {
            if ($data['link_type'] !== $type) {
                $data[$column] = null;
            }
        }

        // Images: a new upload replaces (and deletes) the old file; the
        // "remove" checkbox clears it. Filenames are server-generated by
        // store(), never the client's.
        foreach (['image' => 'remove_image', 'mobile_image' => 'remove_mobile_image'] as $field => $removeFlag) {
            if ($request->hasFile($field)) {
                $this->deleteFiles([$existing?->{$field}]);
                $data[$field] = $request->file($field)->store('home-banners', 'public');
            } elseif ($existing && $request->boolean($removeFlag)) {
                $this->deleteFiles([$existing->{$field}]);
                $data[$field] = null;
            }
        }

        return $data;
    }

    /** @return array<string, mixed> */
    private function formOptions(): array
    {
        return [
            'products' => Product::query()->orderBy('name')->get(['id', 'name']),
            'categories' => Category::query()->orderBy('name')->get(['id', 'name']),
            'tags' => Tag::query()->orderBy('name')->get(['id', 'name']),
        ];
    }
}
